<?php

// This file is generated by scripts/install.php

return array (
  'connections' => 
  array (
    'app' => 
    array (
      'driver' => 'pdo_sqlite',
      'path' => '/home/evan/Desktop/ai/resp/data/app.db',
    ),
    'articles' => 
    array (
      'driver' => 'pdo_sqlite',
      'path' => '/home/evan/Desktop/ai/resp/data/articles.db',
    ),
    'users' => 
    array (
      'driver' => 'pdo_sqlite',
      'path' => '/home/evan/Desktop/ai/resp/data/users.db',
    ),
    'forms' => 
    array (
      'driver' => 'pdo_sqlite',
      'path' => '/home/evan/Desktop/ai/resp/data/forms.db',
    ),
  ),
);
